---
layout: default
title: 履歷範本
---

# {{ page.title }}

---

## 基本資料

- **姓名**：{{ site.resume.name | default: "王大明" }}
- **聯絡電話**：{{ site.resume.phone | default: "0912-345-678" }}
- **電子郵件**：{{ site.resume.email | default: "example@email.com" }}
- **住址**：{{ site.resume.address | default: "台北市大安區仁愛路一段1號" }}
- **LinkedIn／個人網站**：{{ site.resume.website | default: "https://your-website.com" }}

---

## 求職目標

{{ site.resume.objective | default: "請簡述您希望申請的職位及職涯目標。" }}

---

## 學歷

| 學校名稱 | 科系 | 學位 | 就讀期間 |
|----------|------|------|----------|
{% for edu in site.resume.education %}
| {{ edu.school }} | {{ edu.department }} | {{ edu.degree }} | {{ edu.period }} |
{% endfor %}
{% unless site.resume.education %}|    |    |    |    |{% endunless %}

---

## 工作經歷

{% for job in site.resume.experience %}
### {{ job.company }} — {{ job.title }}
在職期間：{{ job.period }}
- {{ job.desc1 }}
- {{ job.desc2 }}
{% endfor %}
{% unless site.resume.experience %}
### 公司名稱 — 職稱
在職期間：YYYY/MM ~ YYYY/MM
- 工作內容或成就1
- 工作內容或成就2
{% endunless %}

---

## 專案經驗

{% for project in site.resume.projects %}
### {{ project.name }}
{{ project.desc }}
{% endfor %}
{% unless site.resume.projects %}
### 專案名稱
說明專案內容、使用技術、擔任角色及貢獻。
{% endunless %}

---

## 技能

{% for skill in site.resume.skills %}
- {{ skill }}
{% endfor %}
{% unless site.resume.skills %}
- 技能1（如：Python、JavaScript）
- 技能2（如：資料分析、專案管理）
{% endunless %}

---

## 語言能力

{% for lang in site.resume.languages %}
- {{ lang.name }}：{{ lang.level }}
{% endfor %}
{% unless site.resume.languages %}
- 國語（中文）：母語／精通／中等／初學
- 英語：精通／中等／初學
{% endunless %}

---

## 證照／獎項

{% for award in site.resume.awards %}
- {{ award.name }} — {{ award.issuer }}，{{ award.date }}
{% endfor %}
{% unless site.resume.awards %}
- 證照或獎項名稱 — 發證／頒發單位，日期
{% endunless %}

---

## 其他補充

{{ site.resume.additional | default: "如有其他可補充之事項（自傳、興趣、推薦人等），可於此說明。" }}

---
